name: Broken Map
description: Report a broken map
title: "[Broken Map]: "
labels: [Broken Map"]
assignees:
  - leha-code
body:
  - type: textarea
    id: map
    attributes:
      label: What map were you on?
      description: Also what version of the map?
      placeholder: Skara Brae v6.9
      value: "Prison Escape 2 v4.2.0"
    validations:
      required: true
  - type: dropdown
    id: versions
    validations: 
      required: true
    attributes:
      label: What versions are you seeing the problem on?
      multiple: true
      options:
        - Pi
        - Reborn
        - PE V0.6.1
        - Survival patch
        - Reborn legacy
  - type: textarea
    id: details
    validations:
      required: true
    attributes:
      label: What are the issues?
      description: Any update blocks? Any broken chests?
  - type: checkboxes
    id: terms
    attributes:
      label: Checklists
      description: Agree to this.
      options:
        - label: I have checked the issues tab for duplicates
          required: true
        - label: This map exists in marketpi-repo
          required: true
        - label: The map I am using is from a version less than v0.9.0
          required: true
